import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  'contributions': [{ type: 'autogenerated', dirName: 'contributions' }]
};

export default sidebars;
